apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiware-orion.fullname" . }}
  labels:
    {{- include "fiware-orion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{/*      protocol: TCP*/}}
      name: {{ .Values.service.name }}
  selector:
    {{- include "fiware-orion.selectorLabels" . | nindent 4 }}
